name: Run E2E Tests React-app

on:
  push:
    branches:
      - 'POC'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clone stx repository
        run: git clone https://${{ secrets.GHA_ACCESS_TOKEN }}@github.com/ChartIQ/stx.git -b POC && ls -a

      - name: Install dependencies for stx
        working-directory: ./stx
        run: npm install

#      - name: Install dependencies for app
#        run: npm install

      - name: Install dependencies for tests
        run: npm install

      - name: Build project-test
        run: npm run build:test

      - name: Build project-chartiq
        run: npm run build:chartiq

      - name: Run e2e-new tests
        run: npm run test-new
        if: ${{ always() }}

      - name: Generate allure report
        if: always()
        run: npm run report-ci
        continue-on-error: true

#      - name: Sync Allure to S3
#          run: aws s3 sync ./spec/e2e-new/allure-report/ s3://stx-allurereports.chartiq.com/${{ github.sha }} --acl public-read --delete
#          env:
#            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#              AWS_REGION: "us-east-1" # optional: defaults to us-east-1
#          if: ${{ always() }}
#
#            - name: Show the allure report location
#              run: echo http://stx-allurereports.chartiq.com.s3-website-us-east-1.amazonaws.com/${{ github.sha }}/
#              if: ${{ always() }}
#
#            - name: Upload Allure Report
#              uses: actions/upload-artifact@v2
#              with:
#                name: allure report
#                path: ./spec/e2e-new/allure-report
#              if: ${{ always() }}
#
