name: Run E2E Tests React-app

on:
  workflow_dispatch:
    inputs:
      testBranch:
        description: 'React App branch name'
        required: true
      stxBranch:
        description: 'Stx branch name'
        required: true
  push:

env:
  # If available, use the react-app branch from the dispatch UI input, otherwise use the branch from the triggering event (commit).
  TEST_BRANCH: ${{ github.event.inputs.testBranch != NaN && github.event.inputs.testBranch || github.event.client_payload.github.event.head_commit.test_branch != NaN && github.event.client_payload.github.event.head_commit.test_branch }}
  STX_BRANCH: ${{ github.event.inputs.stxBranch != NaN && github.event.inputs.stxBranch || github.event.client_payload.github.event.head_commit.stx_branch != NaN && github.event.client_payload.github.event.head_commit.stx_branch || 'master' }}
  CHROMEDRIVER: ${{ secrets.CHROMEDRIVER_VERSION }}
  GECKODRIVER: ${{ secrets.GECKODRIVER_VERSION }}

jobs:
  chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ChartIQ/chartiq-react-app-private
          ref: ${{ env.TEST_BRANCH != NaN && env.TEST_BRANCH }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/New_York"

      - name: Clone stx repository
        run: git clone https://${{ secrets.GHA_ACCESS_TOKEN }}@github.com/ChartIQ/stx.git -b ${{ env.STX_BRANCH != NaN && env.STX_BRANCH }}

      - name: Install dependencies for app
        run: npm install

      - name: Install dependencies for e2e
        working-directory: ./stx/tests/e2e-v2
        run: npm install

      - name: Install dependencies for stx
        working-directory: ./stx
        run: npm install

      - name: Show secrets.CHROMEDRIVER_VERSION
        run: echo ${{env.CHROMEDRIVER}} | sed 's/./& /g'

      - name: Install chromedriver version from secret
        if: ${{ env.CHROMEDRIVER != NaN && env.CHROMEDRIVER != '' && env.CHROMEDRIVER }}
        working-directory: ./stx/tests
        run: npm install chromedriver@${{ env.CHROMEDRIVER }}

      - name: Build project-test
        run: npm run build:test

      - name: Build project-chartiq
        run: npm run build:chartiq

      - name: Prepare application
        run: npm run ciq-prep-app

      - name: Check tests groups
        run: npm run check-specs

      - name: Run e2e-v2 tests with Chrome browser
        run: npm run test-chrome-ci

      - name: Save allure-results artifact
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@master
        with:
          name: allure-chrome
          path: allure-results

  firefox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ChartIQ/chartiq-react-app-private
          ref: ${{ env.TEST_BRANCH != NaN && env.TEST_BRANCH }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/New_York"

      - name: Clone stx repository
        run: git clone https://${{ secrets.GHA_ACCESS_TOKEN }}@github.com/ChartIQ/stx.git -b ${{ env.STX_BRANCH != NaN && env.STX_BRANCH }}

      - name: Install dependencies for app
        run: npm install

      - name: Install dependencies for e2e
        working-directory: ./stx/tests/e2e-v2
        run: npm install

      - name: Install dependencies for stx
        working-directory: ./stx
        run: npm install

      - name: Show secrets.GECKODRIVER_VERSION
        run: echo ${{env.GECKODRIVER}} | sed 's/./& /g'

      - name: Install geckodriver secret version
        if: ${{ env.GECKODRIVER != NaN && env.GECKODRIVER != '' && env.GECKODRIVER }}
        working-directory: ./stx/tests
        run: npm install geckodriver@${{ env.GECKODRIVER }}

      - name: Build project-test
        run: npm run build:test

      - name: Build project-chartiq
        run: npm run build:chartiq

      - name: Prepare application
        run: npm run ciq-prep-app

      - name: Check tests groups
        run: npm run check-specs

      - name: Run e2e-v2 tests with Firefox browser
        run: npm run test-ff-ci

      - name: Save allure-results artifact
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@master
        with:
          name: allure-ff
          path: allure-results

  allure:
    runs-on: ubuntu-latest
    needs: [chrome, firefox]
    if: ${{ !cancelled() }}
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ChartIQ/chartiq-react-app-private
          ref: ${{ env.TEST_BRANCH != NaN && env.TEST_BRANCH }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/New_York"

      - name: Clone stx repository
        run: git clone https://${{ secrets.GHA_ACCESS_TOKEN }}@github.com/ChartIQ/stx.git -b ${{ env.STX_BRANCH != NaN && env.STX_BRANCH }}

      - name: Build project-test
        run: npm run build:test

      - name: Load allure-results from Chrome
        uses: actions/download-artifact@master
        with:
          name: allure-chrome
          path: "./allure-results"

      - name: Load allure-results from Firefox
        uses: actions/download-artifact@master
        with:
          name: allure-ff
          path: "./allure-results"

      - name: Generate allure report
        if: ${{ failure() || success() }}
        run: npm run report-ci
        continue-on-error: true

      - name: Sync Allure to S3
        if: ${{ failure() || success() }}
        run: aws s3 sync ./allure-report/ s3://react-app-allurereports.chartiq.com/${{ github.sha }} --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # optional: defaults to us-east-1

      - name: Show the allure report location
        if: ${{ failure() || success() }}
        run: echo http://react-app-allurereports.chartiq.com.s3-website-us-east-1.amazonaws.com/${{ github.sha }}/
